version: '3.8'

services:
  python-kafka-tensorflow:
    image: python:3.8-slim
    command: tail -f /dev/null
    volumes:
      - whisper_text_generator:/data  
    tty: true  
    container_name: whisper-text-generator-container
    environment:
      - TZ=America/Detroit
      - RELEASE_VERSION=${RELEASE_VERSION}
      - SOURCE_TOPIC_NAME=${SOURCE_TOPIC_NAME}
      - GROUP_ID=${GROUP_ID}
      - BROKER=${BROKER}
    networks:
      - alpine-net
    entrypoint: |
      /bin/bash -c "
      apt-get update && apt-get install -y --no-install-recommends git curl python3-venv;
      python3 -m venv /venv;
      source /venv/bin/activate;
      pip install --no-cache-dir pytz kafka-python python-dotenv tensorflow schedule flask;

      if [ ! -d /data/whisper-text-generator-v${RELEASE_VERSION} ]; then
        mkdir -p /data/whisper-text-generator-v${RELEASE_VERSION} && \
        curl -L https://github.com/DevinMB/whisper-text-generator/archive/refs/tags/v${RELEASE_VERSION}.tar.gz | tar xz --strip-components=1 -C /data/whisper-text-generator-v${RELEASE_VERSION};
      fi
      
      python3 /data/whisper-text-generator-v${RELEASE_VERSION}/whisper-text-generator.py;
      "

networks:
  alpine-net:
    driver: bridge

volumes:
  whisper_text_generator:  
